---
- name: add user
  raw: id user-name || useradd user-name
- name: modify passwd user-name
  raw: echo 'your-password' | passwd user-name --stdin
- name: modify group
  raw: usermod -g wheel user-name
- name: mkdir home
  raw: ls /home/user-name/.ssh || mkdir -p /home/user-name/.ssh
- name: copy public key
  copy: src=your-privity-key.pub dest=/home/user-name/.ssh/authorized_keys
- name: chown home
  raw: chown -R user-name.user-name /home/user-name/.ssh
- name: add ssh config group
  lineinfile: dest=/etc/ssh/sshd_config line='Match group wheel'
- name: add ssh config deny password login
  lineinfile: dest=/etc/ssh/sshd_config line='    PasswordAuthentication no'
- name: add sudoer
  lineinfile: dest=/etc/sudoers line='%wheel        ALL=(ALL)       ALL'
